#!/usr/bin/env bash

set -e

git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"

DIR=$(cd "$(dirname "$0")"; pwd -P)

if [ -n "$START_DATE" ]; then
  TARGET_DAYS=$($DIR/determine_target_days --start $START_DATE $FORCE)
else
  TARGET_DAYS=$($DIR/determine_target_days $FORCE)
fi

$DIR/cleanup

generate_data() {
  DIR=$1
  TARGET_DAY=$2

  echo "Creating repo for $TARGET_DAY"

  REPO_REMOTE_URL=$($DIR/create_target_repo --name $TARGET_DAY)

  REPO_PATH=$(echo $DIR/../output/$TARGET_DAY)

  rm -rf $REPO_PATH

  git clone $REPO_REMOTE_URL $REPO_PATH
  git -C $REPO_PATH checkout gh-pages 2>/dev/null || git -C $REPO_PATH checkout -b gh-pages

  rm -rf $REPO_PATH/**/*

  echo "Start processing data for $TARGET_DAY"

  python $DIR/../generate_data.py $TARGET_DAY

  echo "Done processing data for $TARGET_DAY"

  if [ -n "$(git -C $REPO_PATH status --porcelain)" ]; then
    echo "Start uploading data for $TARGET_DAY"

    git -C $REPO_PATH add -A
    git -C $REPO_PATH commit -m "Data created/updated for $TARGET_DAY." -q

    git -C $REPO_PATH push -u origin gh-pages

    echo "Done uploading data for $TARGET_DAY"
  else
    echo "No data changed, proceed to next day"
  fi
}

for TARGET_DAY in $TARGET_DAYS
do
  generate_data "$DIR" "$TARGET_DAY"
done

wait
echo "Finished"
