#!/usr/bin/env bash

set -e

git config --global user.name $GIT_USER_NAME
git config --global user.email $GIT_USER_EMAIL

DIR=$(cd "$(dirname "$0")"; pwd -P)

TARGET_DAY=$($DIR/determine_target_day)

while [ "$TARGET_DAY" != "None" ]
do
  $DIR/cleanup

  echo "Start processing data for $TARGET_DAY"

  python $DIR/../generate_data.py $TARGET_DAY

  echo "Done processing data for $TARGET_DAY"
  echo "Start uploading data for $TARGET_DAY"

  REPO_PATH=$(echo $DIR/../output)

  git init $REPO_PATH
  git -C $REPO_PATH checkout -b gh-pages
  git -C $REPO_PATH add -A
  git -C $REPO_PATH commit -m "Data created for $TARGET_DAY."

  $DIR/create_target_repo $TARGET_DAY

  git -C $REPO_PATH remote add origin https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_ORG_NAME/$TARGET_DAY.git
  git -C $REPO_PATH push -u origin gh-pages

  echo "Done uploading data for $TARGET_DAY"

  TARGET_DAY=$($DIR/determine_target_day)
done

echo "Finished"
