#!/usr/bin/env python
import os
import argparse
from github import GithubException as GitHubException
from github import Github as GitHub


def create_repo(name, force):
    try:
        gh = GitHub(os.environ.get('GITHUB_ACCESS_TOKEN'))
        gh.get_organization(os.environ.get('GITHUB_ORG_NAME')).create_repo(name)
    except GitHubException as e:
        print('Repo creation error: ', e)
        if not force:
            raise e


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--force', action='store_true')
    parser.add_argument('-n', '--name')
    settings = parser.parse_args()

    create_repo(settings.name, settings.force)
