#!/usr/bin/env bash

DIR=$(cd "$(dirname "$0")"; pwd -P)
mkdir -p "$DIR/../tmp"
LOG_PATH="$DIR/../tmp/timetables-cron.log"

$DIR/crawl &> $LOG_PATH

if [ $? != 0 ]; then
  curl -X POST https://slack.com/api/files.upload \
       -F token=$SLACK_BOT_TOKEN -F channels=test \
       -F initial_comment="Timetable Cron Job Failed!" \
       -F file="@$LOG_PATH"
fi
