#!/usr/bin/env python
import os
import re
from github import Github as GitHub
from datetime import date, timedelta

gh = GitHub(os.environ.get('GITHUB_ACCESS_TOKEN'))

all_repos = []
for repo in gh.get_organization(os.environ.get('GITHUB_ORG_NAME')).get_repos():
    if re.match(r'\d{8}', repo.name):
        all_repos.append(repo.name)

today = date.today()
required_days = []
for delta in range(60):
    required_days.append((today + timedelta(days=delta)).strftime('%Y%m%d'))

target_day = 'None'
for required_day in required_days:
    if required_day not in all_repos:
        target_day = required_day
        break

print(target_day)
